"""Arıza / şikâyet kategori etiketleri — ru, da, cs, ro, nl, sk (form_labels ile birleştirilir)."""

from __future__ import annotations

from typing import Any

_EXTRA: dict[str, dict[str, dict[str, str]]] = {
    "fault": {
        "hvac": {
            "da": "Klima / varme",
            "nl": "Klimaat / verwarming",
            "cs": "Klimatizace / vytápění",
            "ro": "Climatizare / încălzire",
            "sk": "Klimatizácia / kúrenie",
            "ru": "Климат / отопление",
        },
        "electric": {
            "da": "Elektricitet",
            "nl": "Elektriciteit",
            "cs": "Elektřina",
            "ro": "Electricitate",
            "sk": "Elektrina",
            "ru": "Электричество",
        },
        "water_bathroom": {
            "da": "Vand / badeværelse",
            "nl": "Water / badkamer",
            "cs": "Voda / koupelna",
            "ro": "Apă / baie",
            "sk": "Voda / kúpeľňa",
            "ru": "Вода / ванная",
        },
        "tv_electronics": {
            "da": "TV / elektronik",
            "nl": "TV / elektronica",
            "cs": "TV / elektronika",
            "ro": "TV / electronică",
            "sk": "TV / elektronika",
            "ru": "ТВ / электроника",
        },
        "door_lock": {
            "da": "Dørlås",
            "nl": "Deurslot",
            "cs": "Zámek dveří",
            "ro": "Broască ușă",
            "sk": "Zámok dverí",
            "ru": "Дверной замок",
        },
        "furniture_item": {
            "da": "Møbler",
            "nl": "Meubilair",
            "cs": "Nábytek",
            "ro": "Mobilier",
            "sk": "Nábytok",
            "ru": "Мебель",
        },
        "cleaning_equipment_damage": {
            "da": "Skade på rengøringsudstyr",
            "nl": "Schade aan schoonmaakmateriaal",
            "cs": "Poškození úklidového vybavení",
            "ro": "Deteriorare echipament curățenie",
            "sk": "Poškodenie upratovacieho vybavenia",
            "ru": "Повреждение уборочного оборудования",
        },
        "balcony_window": {
            "da": "Altan / vindue",
            "nl": "Balkon / raam",
            "cs": "Balkón / okno",
            "ro": "Balcon / fereastră",
            "sk": "Balkón / okno",
            "ru": "Балкон / окно",
        },
        "other": {
            "da": "Andet",
            "nl": "Overig",
            "cs": "Jiné",
            "ro": "Altele",
            "sk": "Iné",
            "ru": "Другое",
        },
    },
    "complaint": {
        "room_cleaning": {
            "da": "Rengøring af værelse",
            "nl": "Kamerschoonmaak",
            "cs": "Úklid pokoje",
            "ro": "Curățenie cameră",
            "sk": "Upchatie izby",
            "ru": "Уборка номера",
        },
        "noise": {
            "da": "Støj",
            "nl": "Geluidsoverlast",
            "cs": "Hluk",
            "ro": "Zgomot",
            "sk": "Hluk",
            "ru": "Шум",
        },
        "climate": {
            "da": "Klima / varme",
            "nl": "Klimaat",
            "cs": "Klima",
            "ro": "Climat",
            "sk": "Klíma",
            "ru": "Климат",
        },
        "room_comfort": {
            "da": "Værelseskomfort",
            "nl": "Kamercomfort",
            "cs": "Komfort pokoje",
            "ro": "Confort cameră",
            "sk": "Komfort izby",
            "ru": "Комфорт номера",
        },
        "minibar": {
            "da": "Minibar",
            "nl": "Minibar",
            "cs": "Minibar",
            "ro": "Minibar",
            "sk": "Minibar",
            "ru": "Мини-бар",
        },
        "restaurant_service": {
            "da": "Restaurantservice",
            "nl": "Restaurantbediening",
            "cs": "Obsluha v restauraci",
            "ro": "Serviciu restaurant",
            "sk": "Obsluha v reštaurácii",
            "ru": "Обслуживание в ресторане",
        },
        "staff_behavior": {
            "da": "Personalets adfærd",
            "nl": "Gedrag personeel",
            "cs": "Chování personálu",
            "ro": "Comportament personal",
            "sk": "Správanie personálu",
            "ru": "Поведение персонала",
        },
        "general_areas": {
            "da": "Fællesområder",
            "nl": "Algemene ruimtes",
            "cs": "Společné prostory",
            "ro": "Zone comune",
            "sk": "Spoločné priestory",
            "ru": "Общие зоны",
        },
        "hygiene": {
            "da": "Hygiejne",
            "nl": "Hygiëne",
            "cs": "Hygiena",
            "ro": "Igienă",
            "sk": "Hygiena",
            "ru": "Гигиена",
        },
        "internet_tv": {
            "da": "Internet / TV",
            "nl": "Internet / TV",
            "cs": "Internet / TV",
            "ro": "Internet / TV",
            "sk": "Internet / TV",
            "ru": "Интернет / ТВ",
        },
        "lost_property": {
            "da": "Mistet ejendom",
            "nl": "Verloren voorwerp",
            "cs": "Ztracený majetek",
            "ro": "Obiect pierdut",
            "sk": "Stratený majetok",
            "ru": "Утерянные вещи",
        },
        "other": {
            "da": "Andet",
            "nl": "Overig",
            "cs": "Jiné",
            "ro": "Altele",
            "sk": "Iné",
            "ru": "Другое",
        },
    },
    "guest_notification": {
        "allergen_notice": {
            "da": "Allergenoplysning",
            "nl": "Allergenenmelding",
            "cs": "Upozornění na alergeny",
            "ro": "Notificare alergeni",
            "sk": "Upozornenie na alergény",
            "ru": "Уведомление об аллергенах",
        },
        "gluten_sensitivity": {
            "da": "Glutenfølsomhed",
            "nl": "Glutengevoeligheid",
            "cs": "Citlivost na lepek",
            "ro": "Sensibilitate la gluten",
            "sk": "Citlivosť na lepok",
            "ru": "Чувствительность к глютену",
        },
        "lactose_sensitivity": {
            "da": "Laktosefølsomhed",
            "nl": "Lactosegevoeligheid",
            "cs": "Citlivost na laktozu",
            "ro": "Intoleranță la lactoză",
            "sk": "Citlivosť na laktózu",
            "ru": "Непереносимость лактозы",
        },
        "vegan_vegetarian": {
            "da": "Vegan / vegetar",
            "nl": "Veganistisch / vegetarisch",
            "cs": "Vegan / vegetarián",
            "ro": "Vegan / vegetarian",
            "sk": "Vegán / vegetarián",
            "ru": "Веган / вегетарианство",
        },
        "food_sensitivity_general": {
            "da": "Generel madfølsomhed",
            "nl": "Algemene voedselintolerantie",
            "cs": "Obecná potravinová intolerance",
            "ro": "Sensibilitate alimentară generală",
            "sk": "Všeobecná potravinová citlivosť",
            "ru": "Общая пищевая чувствительность",
        },
        "chronic_condition": {
            "da": "Kronisk tilstand",
            "nl": "Chronische aandoening",
            "cs": "Chronické onemocnění",
            "ro": "Afecțiune cronică",
            "sk": "Chronické ochorenie",
            "ru": "Хроническое заболевание",
        },
        "accessibility_special_needs": {
            "da": "Tilgængelighed / særlige behov",
            "nl": "Toegankelijkheid / bijzondere behoeften",
            "cs": "Bezbariérový přístup / speciální potřeby",
            "ro": "Accesibilitate / nevoi speciale",
            "sk": "Bezbariérový prístup / špeciálne potreby",
            "ru": "Доступность / особые потребности",
        },
        "pregnancy": {
            "da": "Graviditet",
            "nl": "Zwangerschap",
            "cs": "Těhotenství",
            "ro": "Sarcină",
            "sk": "Tehotenstvo",
            "ru": "Беременность",
        },
        "medication_health_sensitivity": {
            "da": "Medicin / sundhed",
            "nl": "Medicatie / gezondheid",
            "cs": "Léky / zdravotní citlivost",
            "ro": "Medicație / sănătate",
            "sk": "Lieky / zdravotná citlivosť",
            "ru": "Лекарства / здоровье",
        },
        "other_health": {
            "da": "Andet (sundhed)",
            "nl": "Overig (gezondheid)",
            "cs": "Jiné (zdraví)",
            "ro": "Altele (sănătate)",
            "sk": "Iné (zdravie)",
            "ru": "Другое (здоровье)",
        },
        "birthday_celebration": {
            "da": "Fødselsdagsfejring",
            "nl": "Verjaardagsviering",
            "cs": "Oslava narozenin",
            "ro": "Zi de naștere / aniversare",
            "sk": "Oslava narodenín",
            "ru": "День рождения",
        },
        "honeymoon_anniversary": {
            "da": "Bryllupsrejse / jubilæum",
            "nl": "Huwelijksreis / jubileum",
            "cs": "Svatební cesta / výročí",
            "ro": "Lună de miere / aniversare",
            "sk": "Svadobná cesta / výročie",
            "ru": "Медовый месяц / годовщина",
        },
        "surprise_organization": {
            "da": "Surprise-arrangement",
            "nl": "Verrassingsarrangement",
            "cs": "Překvapivá organizace",
            "ro": "Organizare surpriză",
            "sk": "Prekvapivá organizácia",
            "ru": "Организация сюрприза",
        },
        "room_decoration": {
            "da": "Værelsesdekoration",
            "nl": "Kamerdecoratie",
            "cs": "Dekorace pokoje",
            "ro": "Decor cameră",
            "sk": "Dekorácia izby",
            "ru": "Оформление номера",
        },
        "other_celebration": {
            "da": "Andet (fejring)",
            "nl": "Overig (viering)",
            "cs": "Jiné (oslava)",
            "ro": "Altele (sărbătoare)",
            "sk": "Iné (oslava)",
            "ru": "Другое (праздник)",
        },
        "late_checkout": {
            "da": "Sen udtjekning",
            "nl": "Late check-out",
            "cs": "Pozdní odhlášení",
            "ro": "Check-out tardiv",
            "sk": "Neskoré odhlásenie",
            "ru": "Поздний выезд",
        },
    },
}


def merge_extra_lang_columns(category_labels: dict[str, Any]) -> None:
    for intent, by_cat in _EXTRA.items():
        for cat_id, langs in by_cat.items():
            if intent in category_labels and cat_id in category_labels[intent]:
                category_labels[intent][cat_id].update(langs)
