from typing import Dict


TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "tr": {
        "chitchat_greeting": "Merhaba, ben Viona; Kaila Beach Hotel'deki dijital asistanınızım. Size nasıl yardımcı olabilirim?",
        "chitchat_assistant_intro": "Ben Viona — Kaila Beach Hotel için çalışan dijital asistanınızım. Otel hizmetleri ve sorularınızda size yardımcı olabilirim.",
        "chitchat_identity_question": "Ben Viona, Kaila Beach Hotel için tasarlanmış dijital asistanım. Otel hizmetleri, konaklama ve genel sorular konusunda yardımcı olabilirim.",
        "chitchat_thanks": "Rica ederim. Konaklamanızla ilgili başka bir konuda yardımcı olabilirim.",
        "chitchat_farewell": "Görüşmek üzere. İhtiyacınız olursa yine buradayım.",
        "chitchat_apology_from_user": "Hiç sorun değil. Size memnuniyetle yardımcı olmaya devam edebilirim.",
        "chitchat_compliment": "Nazik geri bildiriminiz için teşekkür ederim. Yardımcı olabildiysem ne mutlu bana.",
        "chitchat_how_are_you": "Teşekkür ederim, iyiyim. Kaila Beach Hotel ile ilgili sorularınızda yanınızdayım.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "Şu an saat {time}'dir.",
        "fault_redirect_message": "Bu sorun için lütfen Arıza Talep formunu doldurunuz.",
        "complaint_redirect_message": "Bu konu için lütfen Şikayet formunu doldurunuz.",
        "request_redirect_message": "Talebinizi İstek formu üzerinden iletebilirsiniz.",
        "guest_relations_redirect_message": "Bu konu için lütfen Misafir İlişkileri departmanı ile iletişime geçiniz.",
        "reception_fallback_message": "İsteğinizi şu anda tam işleyemedim. Dilerseniz sorunuzu daha kısa şekilde tekrar yazabilirsiniz; size yardımcı olmaya devam edebilirim.",
        "canonical_fallback_safe": "Bu konuda doğrulanmış bilgiye şu anda erişemiyorum. Size en doğru destek için lütfen resepsiyon ile iletişime geçiniz.",
        "canonical_fallback_unavailable": "Şu anda asistana kısa süreli erişim sorunu yaşıyorum. Lütfen birkaç saniye sonra tekrar deneyiniz.",
        "recommendation_fish": "Balık tercih ediyorsanız Mare Restaurant uygun seçeneklerden biridir. A la carte kullanımında rezervasyon gerektiğini hatırlatırım.",
        "recommendation_meat": "Et veya BBQ tercih ediyorsanız Sinton BBQ Restaurant iyi bir seçenektir. A la carte restoranlar için rezervasyon gerekir.",
        "recommendation_pizza_snack": "Pizza veya atıştırmalık için Dolphin Snack, Gusto Snack ve Beach Imbiss uygun seçeneklerdir.",
        "recommendation_coffee_dessert": "Kahve veya tatlı için Libum Cafe ve Lobby Bar ideal seçeneklerdir.",
        "recommendation_kids_activity": "Çocuk aktiviteleri için Mini Club, Mini Disco ve Çocuk Oyun Parkı öne çıkan seçeneklerdir.",
        "recommendation_romantic_dinner": "Romantik bir akşam yemeği için Mare Restaurant veya La Terrace A La Carte uygun seçeneklerdir. A la carte restoranlar için rezervasyon gerekir.",
        "recommendation_general_dining": "Karar veremediyseniz akşam için Sinton BBQ veya Mare Restaurant iyi seçeneklerdir; daha hızlı bir alternatif isterseniz Dolphin Snack ve Gusto Snack tercih edebilirsiniz.",
        "fault_template_with_device": "{device} arızası durumunda lütfen resepsiyon ile iletişime geçiniz; otelde teknik destek sağlanmaktadır.",
        "fault_template_generic": "Bu arıza durumu için lütfen resepsiyon ile iletişime geçiniz; otelde teknik destek sağlanmaktadır.",
        "complaint_noise": "Bu şikayetinizi öncelikle Misafir İlişkileri ile paylaşmanızı öneririm. Gerekirse resepsiyon üzerinden de hızlıca iletebilirsiniz.",
        "complaint_cleanliness": "Temizlikle ilgili bu durumu öncelikle Misafir İlişkileri ile paylaşınız; resepsiyon da destek sağlayabilir.",
        "complaint_default": "Bu şikayet için öncelikle Misafir İlişkileri ile iletişime geçiniz. Dilerseniz resepsiyon üzerinden de iletebilirsiniz.",
        "request_towel": "Havlu talebinizi lütfen resepsiyon ile iletiniz.",
        "request_blanket": "Battaniye talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "request_housekeeping": "Oda temizliği ve housekeeping talepleriniz için resepsiyon ile iletişime geçebilirsiniz; ilgili ekip yönlendirilir.",
        "request_reception_contact": "Bu konuda en hızlı çözüm için lütfen resepsiyon ile doğrudan iletişime geçiniz.",
        "request_guest_relations_contact": "Bu konuda Misafir İlişkileri departmanı en doğru birimdir. Dilerseniz resepsiyon üzerinden de bağlantı sağlayabilirsiniz.",
        "request_transfer": "Transfer talebiniz için lütfen resepsiyon ile iletişime geçiniz; uygun planlama yapılacaktır.",
        "request_lunch_box": "Lunch Box talebi için lütfen en geç saat 20:00'ye kadar resepsiyona bilgi veriniz.",
        "request_default": "Bu talebinizi lütfen resepsiyon ile paylaşınız.",
        "reservation_early_checkin": "Erken giriş talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "reservation_late_checkout": "Geç çıkış talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "reservation_room_change": "Oda değişikliği talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "reservation_default": "Rezervasyonunuzla ilgili bu durum için lütfen resepsiyon ile iletişime geçiniz.",
        "special_need_celiac": "Bu durumunuzu lütfen Misafir İlişkileri departmanına iletiniz; mutfak departmanından uygun destek sağlanabilir.",
        "special_need_vegan": "Beslenme tercihinizi lütfen Misafir İlişkileri departmanına iletiniz; uygun seçenekler konusunda yardımcı olunabilir.",
        "special_need_allergy": "Alerji bilginizi lütfen Misafir İlişkileri departmanına bildiriniz; gerekli yönlendirme sağlanacaktır.",
        "special_need_baby_need": "Bebek beslenmesi ve mama ile ilgili talebinizi lütfen Misafir İlişkileri departmanına iletiniz; uygun seçenekler konusunda yardımcı olacaklardır.",
        "special_need_accessibility_need": "Erişilebilirlik ile ilgili ihtiyacınızı lütfen Misafir İlişkileri departmanına bildiriniz; gerekli düzenlemeler sağlanacaktır.",
        "special_need_default": "Bu durum için lütfen Misafir İlişkileri departmanı ile iletişime geçiniz.",
        "fixed_restaurant_info": "- Ana Restoran: Kahvaltı 07:00-10:00, Geç kahvaltı 10:00-10:30, Öğle yemeği 12:30-14:00, Akşam yemeği 19:00-21:00, Mini gece büfesi 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: Rezervasyonlu ve ücretli.\n- Sinton BBQ: 13:00-22:00 (Pazartesi kapalı).\nSnack ve cafe:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss İçecek 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBarlar:\n- Havuz Bar 10:00-00:00\n- Dondurma Servisi 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 ve 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Özel plaj mevcuttur.\n- Şezlong, şemsiye ve plaj havlusu ücretsizdir.\n- Plaj kullanım saatleri: 08:30-18:30.\nHavuzlar:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 ve 14:00-16:00\n- Kapalı Havuz: 08:00-19:00\n- Çocuk havuzu ve Dolphin Pool da bulunmaktadır.\n- Havuz ve plaj havlusu servisi ücretsizdir.",
        "fixed_spa_info": "- La Serenite Spa kullanım saatleri: 09:00-19:00.\nÜcretsiz alanlar:\n- Sauna\n- Türk hamamı\n- Buhar odası\n- Kapalı havuz\nÜcretli hizmetler:\n- Masaj\n- Peeling\n- Cilt bakımı\n- Diğer bakım hizmetleri\nNot: Temel ıslak alan kullanımı ücretsiz, profesyonel bakım ve terapi hizmetleri ücretlidir.",
        "fixed_animation_info": "- Akşam akrobatik dans şovları, temalı geceler, canlı müzik, DJ performansları.\n- Günlük program 10:00'da başlar; aqua gym, dart, su topu gibi aktiviteler içerir.\nÇocuk aktiviteleri:\n- Jammies Kids Club / Mini Club: 10:00-12:30 ve 14:30-17:00 (4-12 yaş)\n- Mini Disco: 20:45-21:00 (4-12 yaş)\n- Çocuk oyun parkı: 07:00-21:00\nNot: Programlar sezon ve operasyon takvimine göre değişebilir.",
        "fixed_outside_hotel_info": "Otel dışı öneriler için en güncel ve güvenli bilgi resepsiyondadır. Alanya merkez yaklaşık 3 km mesafededir; taksi ve toplu taşıma seçenekleri mevcuttur.",
    },
    "en": {
        "chitchat_greeting": "Hello, I'm Viona, your digital assistant at Kaila Beach Hotel. How can I help you?",
        "chitchat_assistant_intro": "I'm Viona, the digital assistant for Kaila Beach Hotel. I can help you with hotel services, information and practical questions during your stay.",
        "chitchat_identity_question": "I'm Viona, the digital assistant for Kaila Beach Hotel. I can help with hotel services, stay-related questions, and general information.",
        "chitchat_thanks": "You're very welcome. I'm here if you need any help with your stay at Kaila Beach Hotel.",
        "chitchat_farewell": "See you. I'm here whenever you need help during your stay.",
        "chitchat_apology_from_user": "No worries at all. I'm happy to keep helping you.",
        "chitchat_compliment": "Thank you for your kind words. Glad I could help.",
        "chitchat_how_are_you": "I'm doing well, thank you. I'm here to help with anything about Kaila Beach Hotel.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "The current time is {time}.",
        "fault_redirect_message": "For this issue, please complete the Fault Report form.",
        "complaint_redirect_message": "For this matter, please complete the Complaint form.",
        "request_redirect_message": "You can submit your request through the Request form.",
        "guest_relations_redirect_message": "For this matter, please contact the Guest Relations department.",
        "reception_fallback_message": "I couldn't fully process that right now. You can try asking again in a shorter way, and I'll keep helping.",
        "canonical_fallback_safe": "I do not have verified information on this right now. For the most accurate assistance, please contact reception.",
        "canonical_fallback_unavailable": "I am temporarily unavailable at the moment. Please try again in a few seconds.",
        "recommendation_fish": "If you prefer fish, Mare Restaurant is a strong option. Please note that a la carte service requires a reservation.",
        "recommendation_meat": "If you prefer meat or BBQ, Sinton BBQ Restaurant is a great match. A la carte restaurants require a reservation.",
        "recommendation_pizza_snack": "For pizza or snacks, Dolphin Snack, Gusto Snack, and Beach Imbiss are good options.",
        "recommendation_coffee_dessert": "For coffee or desserts, Libum Cafe and Lobby Bar are ideal choices.",
        "recommendation_kids_activity": "For children, Mini Club, Mini Disco, and the Kids Playground are the main activity options.",
        "recommendation_romantic_dinner": "For a romantic dinner, Mare Restaurant or La Terrace A La Carte are suitable options. A reservation is required for a la carte restaurants.",
        "recommendation_general_dining": "If you are undecided, Sinton BBQ or Mare Restaurant are good dinner options; for a quicker bite, Dolphin Snack and Gusto Snack are practical choices.",
        "fault_template_with_device": "If your {device} is not working, please contact reception; technical support is provided at the hotel.",
        "fault_template_generic": "For this fault, please contact reception; technical support is provided at the hotel.",
        "complaint_noise": "Please share this complaint with Guest Relations first. Reception can also assist with escalation if needed.",
        "complaint_cleanliness": "Please report this cleanliness issue to Guest Relations first; reception can also support.",
        "complaint_default": "For this complaint, please contact Guest Relations first. You may also report it via reception.",
        "request_towel": "Please contact reception for your towel request.",
        "request_blanket": "Please contact reception for your blanket request.",
        "request_housekeeping": "For room cleaning and housekeeping requests, please contact reception; the relevant team will be arranged.",
        "request_reception_contact": "For the fastest resolution, please contact reception directly.",
        "request_guest_relations_contact": "For this matter, Guest Relations is the right department. You may also connect through reception.",
        "request_transfer": "For transfer arrangements, please contact reception and the team will assist you.",
        "request_lunch_box": "For a Lunch Box request, please inform reception no later than 20:00.",
        "request_default": "Please share this request with reception.",
        "reservation_early_checkin": "Please contact reception for your early check-in request.",
        "reservation_late_checkout": "Please contact reception for your late check-out request.",
        "reservation_room_change": "Please contact reception for your room change request.",
        "reservation_default": "Please contact reception regarding your reservation request.",
        "special_need_celiac": "Please inform the Guest Relations department about this condition; suitable support can be coordinated with the kitchen.",
        "special_need_vegan": "Please inform the Guest Relations department about your dietary preference; suitable options may be arranged.",
        "special_need_allergy": "Please inform the Guest Relations department about your allergy; necessary guidance will be provided.",
        "special_need_baby_need": "Please contact the Guest Relations department about your baby food needs; they can help arrange suitable options.",
        "special_need_accessibility_need": "Please inform the Guest Relations department about your accessibility needs; the necessary arrangements will be made.",
        "special_need_default": "Please contact the Guest Relations department for this matter.",
        "fixed_restaurant_info": "- Main Restaurant: Breakfast 07:00-10:00, Late breakfast 10:00-10:30, Lunch 12:30-14:00, Dinner 19:00-21:00, Mini night buffet 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: Reservation-only and paid.\n- Sinton BBQ: 13:00-22:00 (closed Mondays).\nSnack and cafe:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss Drinks 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBars:\n- Pool Bar 10:00-00:00\n- Ice Cream Service 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 and 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Private beach available.\n- Sunbeds, umbrellas, and beach towels are free.\n- Beach usage hours: 08:30-18:30.\nPools:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 and 14:00-16:00\n- Indoor Pool: 08:00-19:00\n- Children’s pool and Dolphin Pool are also available.\n- Pool and beach towel service is free.",
        "fixed_spa_info": "- La Serenite Spa hours: 09:00-19:00.\nFree areas:\n- Sauna\n- Turkish bath\n- Steam room\n- Indoor pool\nPaid services:\n- Massage\n- Peeling\n- Skin care\n- Other treatment services\nNote: Basic wet-area use is free; professional care and therapy services are paid.",
        "fixed_animation_info": "- Evening acrobatic dance shows, themed nights, live music, and DJ performances.\n- Daily program starts at 10:00 and includes aqua gym, darts, and water polo.\nChildren’s activities:\n- Jammies Kids Club / Mini Club: 10:00-12:30 and 14:30-17:00 (ages 4-12)\n- Mini Disco: 20:45-21:00 (ages 4-12)\n- Children’s playground: 07:00-21:00\nNote: Programs may vary based on seasonal and operational schedules.",
        "fixed_outside_hotel_info": "For outside-hotel suggestions, reception provides the most up-to-date and safe guidance. Alanya city center is about 3 km away, and taxi/public transport options are available.",
    },
    "de": {
        "chitchat_greeting": "Hallo, ich bin Viona, Ihre digitale Assistentin im Kaila Beach Hotel. Wie kann ich Ihnen helfen?",
        "chitchat_assistant_intro": "Ich bin Viona, die digitale Assistentin des Kaila Beach Hotels. Ich unterstütze Sie bei Services, Informationen und Fragen rund um Ihren Aufenthalt.",
        "chitchat_identity_question": "Ich bin Viona, die digitale Assistentin des Kaila Beach Hotel. Ich helfe Ihnen gern bei Fragen zu Hotelservices und Ihrem Aufenthalt.",
        "chitchat_thanks": "Gern geschehen. Wenn Sie noch Fragen zu Ihrem Aufenthalt haben, helfe ich Ihnen gern weiter.",
        "chitchat_farewell": "Auf Wiedersehen. Ich bin jederzeit für Sie da, wenn Sie Hilfe brauchen.",
        "chitchat_apology_from_user": "Kein Problem. Ich helfe Ihnen gern weiter.",
        "chitchat_compliment": "Vielen Dank für Ihr nettes Feedback. Es freut mich, dass ich helfen konnte.",
        "chitchat_how_are_you": "Danke, mir geht es gut. Ich unterstütze Sie gern bei Fragen rund um das Kaila Beach Hotel.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "Die aktuelle Zeit ist {time}.",
        "fault_redirect_message": "Bitte füllen Sie für dieses Problem das Störungsmeldungsformular aus.",
        "complaint_redirect_message": "Bitte füllen Sie für dieses Thema das Beschwerdeformular aus.",
        "request_redirect_message": "Sie können Ihre Anfrage über das Anfrageformular senden.",
        "guest_relations_redirect_message": "Bitte wenden Sie sich für dieses Thema an die Gästebetreuung.",
        "reception_fallback_message": "Ich konnte Ihre Anfrage gerade nicht vollständig verarbeiten. Versuchen Sie es gern noch einmal in kürzerer Form.",
        "canonical_fallback_safe": "Ich kann dazu derzeit keine verifizierten Informationen bereitstellen. Bitte wenden Sie sich für die sicherste Auskunft an die Rezeption.",
        "canonical_fallback_unavailable": "Ich bin momentan kurzzeitig nicht erreichbar. Bitte versuchen Sie es in wenigen Sekunden erneut.",
        "recommendation_fish": "Wenn Sie Fisch bevorzugen, ist das Mare Restaurant eine sehr gute Option. Bitte beachten Sie: Für A-la-carte ist eine Reservierung erforderlich.",
        "recommendation_meat": "Wenn Sie Fleisch oder BBQ bevorzugen, passt das Sinton BBQ Restaurant sehr gut. Für A-la-carte-Restaurants ist eine Reservierung erforderlich.",
        "recommendation_pizza_snack": "Für Pizza oder Snacks sind Dolphin Snack, Gusto Snack und Beach Imbiss passende Optionen.",
        "recommendation_coffee_dessert": "Für Kaffee oder Dessert sind Libum Cafe und Lobby Bar ideale Optionen.",
        "recommendation_kids_activity": "Für Kinderaktivitäten sind Mini Club, Mini Disco und der Kinderspielplatz die wichtigsten Optionen.",
        "recommendation_romantic_dinner": "Für ein romantisches Abendessen sind Mare Restaurant oder La Terrace A La Carte passende Optionen. Für A-la-carte-Restaurants ist eine Reservierung erforderlich.",
        "recommendation_general_dining": "Wenn Sie unsicher sind, sind Sinton BBQ oder Mare Restaurant gute Optionen für den Abend; für einen schnellen Snack eignen sich Dolphin Snack und Gusto Snack.",
        "fault_template_with_device": "Bei einem {device}-Defekt wenden Sie sich bitte an die Rezeption; im Hotel wird technischer Support bereitgestellt.",
        "fault_template_generic": "Bei dieser Störung wenden Sie sich bitte an die Rezeption; im Hotel wird technischer Support bereitgestellt.",
        "complaint_noise": "Bitte wenden Sie sich mit dieser Beschwerde zuerst an die Gästebetreuung. Bei Bedarf kann auch die Rezeption unterstützen.",
        "complaint_cleanliness": "Bitte melden Sie dieses Reinigungsproblem zunächst der Gästebetreuung; die Rezeption kann ebenfalls helfen.",
        "complaint_default": "Bitte wenden Sie sich bei dieser Beschwerde zuerst an die Gästebetreuung. Alternativ kann die Rezeption unterstützen.",
        "request_towel": "Bitte wenden Sie sich für Ihre Handtuchanfrage an die Rezeption.",
        "request_blanket": "Bitte wenden Sie sich für Ihre Deckenanfrage an die Rezeption.",
        "request_housekeeping": "Für Zimmerreinigung und Housekeeping-Anfragen wenden Sie sich bitte an die Rezeption; das zuständige Team wird informiert.",
        "request_reception_contact": "Für die schnellste Lösung wenden Sie sich bitte direkt an die Rezeption.",
        "request_guest_relations_contact": "Für dieses Anliegen ist die Gästebetreuung die richtige Stelle. Auf Wunsch kann die Rezeption ebenfalls verbinden.",
        "request_transfer": "Für Transferanfragen wenden Sie sich bitte an die Rezeption; die Planung wird dort koordiniert.",
        "request_lunch_box": "Für eine Lunch-Box-Anfrage informieren Sie bitte die Rezeption spätestens bis 20:00 Uhr.",
        "request_default": "Bitte teilen Sie diese Anfrage der Rezeption mit.",
        "reservation_early_checkin": "Bitte wenden Sie sich für Ihre Bitte um frühen Check-in an die Rezeption.",
        "reservation_late_checkout": "Bitte wenden Sie sich für Ihre Bitte um späten Check-out an die Rezeption.",
        "reservation_room_change": "Bitte wenden Sie sich für Ihren Zimmerwechsel an die Rezeption.",
        "reservation_default": "Bitte wenden Sie sich bezüglich Ihrer Reservierung an die Rezeption.",
        "special_need_celiac": "Bitte informieren Sie die Gästebetreuung über diese Situation; geeignete Unterstützung kann mit der Küche koordiniert werden.",
        "special_need_vegan": "Bitte informieren Sie die Gästebetreuung über Ihre Ernährungspräferenz; passende Optionen können angeboten werden.",
        "special_need_allergy": "Bitte informieren Sie die Gästebetreuung über Ihre Allergie; die notwendige Unterstützung wird bereitgestellt.",
        "special_need_baby_need": "Bitte wenden Sie sich an die Gästebetreuung bezüglich Ihres Bedarfs an Babynahrung; geeignete Optionen können organisiert werden.",
        "special_need_accessibility_need": "Bitte informieren Sie die Gästebetreuung über Ihre Bedürfnisse im Bereich Barrierefreiheit; die notwendigen Vorkehrungen werden getroffen.",
        "special_need_default": "Bitte wenden Sie sich in diesem Fall an die Gästebetreuung.",
        "fixed_restaurant_info": "- Hauptrestaurant: Frühstück 07:00-10:00, Spätfrühstück 10:00-10:30, Mittagessen 12:30-14:00, Abendessen 19:00-21:00, Mini-Nachtbuffet 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: Reservierungspflichtig und kostenpflichtig.\n- Sinton BBQ: 13:00-22:00 (montags geschlossen).\nSnack und Cafe:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss Getränke 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBars:\n- Pool Bar 10:00-00:00\n- Eis-Service 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 und 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Privater Strand ist vorhanden.\n- Liegen, Sonnenschirme und Strandhandtücher sind kostenlos.\n- Strandnutzung: 08:30-18:30.\nPools:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 und 14:00-16:00\n- Hallenbad: 08:00-19:00\n- Kinderbecken und Dolphin Pool sind ebenfalls verfügbar.\n- Handtuchservice für Pool und Strand ist kostenlos.",
        "fixed_spa_info": "- Öffnungszeiten La Serenite Spa: 09:00-19:00.\nKostenlose Bereiche:\n- Sauna\n- Türkisches Bad\n- Dampfbad\n- Hallenbad\nKostenpflichtige Leistungen:\n- Massage\n- Peeling\n- Hautpflege\n- Weitere Behandlungen\nHinweis: Grundnutzung der Nassbereiche ist kostenlos; professionelle Pflege- und Therapieleistungen sind kostenpflichtig.",
        "fixed_animation_info": "- Abendliche Akrobatik-Tanzshows, Themenabende, Live-Musik und DJ-Performances.\n- Tagesprogramm startet um 10:00 mit Aqua Gym, Dart und Wasserball.\nKinderaktivitäten:\n- Jammies Kids Club / Mini Club: 10:00-12:30 und 14:30-17:00 (4-12 Jahre)\n- Mini Disco: 20:45-21:00 (4-12 Jahre)\n- Kinderspielplatz: 07:00-21:00\nHinweis: Programme können je nach Saison- und Betriebsplan variieren.",
        "fixed_outside_hotel_info": "Für Empfehlungen außerhalb des Hotels wenden Sie sich bitte an die Rezeption; dort erhalten Sie die aktuellsten und sichersten Informationen. Das Zentrum von Alanya ist etwa 3 km entfernt; Taxi- und ÖPNV-Optionen sind verfügbar.",
    },
    "ru": {
        "chitchat_greeting": "Здравствуйте! Я Виона, ваш цифровой ассистент в отеле Kaila Beach. Чем могу помочь?",
        "chitchat_assistant_intro": "Я Виона, цифровой ассистент отеля Kaila Beach. Помогу с услугами отеля, информацией и вопросами во время вашего проживания.",
        "chitchat_identity_question": "Я Viona, цифровой помощник Kaila Beach Hotel. Я могу помочь с услугами отеля, проживанием и общими вопросами.",
        "chitchat_thanks": "Пожалуйста. Если у вас будут ещё вопросы по отелю или проживанию, я помогу.",
        "chitchat_farewell": "До встречи. Если понадобится помощь, я рядом.",
        "chitchat_apology_from_user": "Ничего страшного. Я с удовольствием продолжу помогать вам.",
        "chitchat_compliment": "Спасибо за тёплые слова. Рада, что смогла помочь.",
        "chitchat_how_are_you": "Спасибо, у меня всё хорошо. Я рядом, чтобы помочь с вопросами по Kaila Beach Hotel.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "Текущее время: {time}.",
        "fault_redirect_message": "По этой проблеме, пожалуйста, заполните форму заявки о неисправности.",
        "complaint_redirect_message": "По этому вопросу, пожалуйста, заполните форму жалобы.",
        "request_redirect_message": "Вы можете отправить запрос через форму запроса.",
        "guest_relations_redirect_message": "По этому вопросу, пожалуйста, свяжитесь со службой по работе с гостями.",
        "reception_fallback_message": "Сейчас я не смогла полностью обработать ваш запрос. Попробуйте, пожалуйста, написать его короче, и я продолжу помогать.",
        "canonical_fallback_safe": "Сейчас у меня нет подтвержденной информации по этому вопросу. Для наиболее точной помощи, пожалуйста, обратитесь на ресепшн.",
        "canonical_fallback_unavailable": "Сейчас я временно недоступна. Пожалуйста, попробуйте снова через несколько секунд.",
        "recommendation_fish": "Если вы предпочитаете рыбу, Mare Restaurant — один из лучших вариантов. Для a la carte требуется предварительное бронирование.",
        "recommendation_meat": "Если вы предпочитаете мясо или BBQ, Sinton BBQ Restaurant отлично подойдет. Для a la carte ресторанов требуется бронирование.",
        "recommendation_pizza_snack": "Для пиццы и закусок подойдут Dolphin Snack, Gusto Snack и Beach Imbiss.",
        "recommendation_coffee_dessert": "Для кофе и десертов лучше всего подойдут Libum Cafe и Lobby Bar.",
        "recommendation_kids_activity": "Для детей основными вариантами являются Mini Club, Mini Disco и детская игровая площадка.",
        "recommendation_romantic_dinner": "Для романтического ужина подойдут Mare Restaurant или La Terrace A La Carte. Для a la carte ресторанов требуется предварительное бронирование.",
        "recommendation_general_dining": "Если сложно выбрать, на ужин подойдут Sinton BBQ или Mare Restaurant; для более быстрого перекуса удобны Dolphin Snack и Gusto Snack.",
        "fault_template_with_device": "В случае неисправности ({device}) пожалуйста, обратитесь на ресепшн; в отеле предоставляется техническая поддержка.",
        "fault_template_generic": "При этой неисправности, пожалуйста, обратитесь на ресепшн; в отеле предоставляется техническая поддержка.",
        "complaint_noise": "Пожалуйста, сначала сообщите об этой жалобе в службу по работе с гостями. При необходимости поможет и ресепшн.",
        "complaint_cleanliness": "Пожалуйста, сначала сообщите о проблеме с чистотой в службу по работе с гостями; ресепшн также может помочь.",
        "complaint_default": "По этой жалобе, пожалуйста, сначала обратитесь в службу по работе с гостями. Также можно передать через ресепшн.",
        "request_towel": "Пожалуйста, обратитесь на ресепшн по вопросу полотенца.",
        "request_blanket": "Пожалуйста, обратитесь на ресепшн по вопросу одеяла.",
        "request_housekeeping": "По вопросам уборки и housekeeping, пожалуйста, обратитесь на ресепшн; нужная команда будет направлена.",
        "request_reception_contact": "Для самого быстрого решения, пожалуйста, свяжитесь с ресепшн напрямую.",
        "request_guest_relations_contact": "По этому вопросу наиболее подходящий отдел — служба по работе с гостями. Также можно обратиться через ресепшн.",
        "request_transfer": "По вопросам трансфера, пожалуйста, обратитесь на ресепшн; они помогут с организацией.",
        "request_lunch_box": "Для заказа Lunch Box, пожалуйста, сообщите на ресепшн не позднее 20:00.",
        "request_default": "Пожалуйста, передайте этот запрос на ресепшн.",
        "reservation_early_checkin": "Пожалуйста, обратитесь на ресепшн по вопросу раннего заезда.",
        "reservation_late_checkout": "Пожалуйста, обратитесь на ресепшн по вопросу позднего выезда.",
        "reservation_room_change": "Пожалуйста, обратитесь на ресепшн по вопросу смены номера.",
        "reservation_default": "Пожалуйста, обратитесь на ресепшн по вашему запросу по бронированию.",
        "special_need_celiac": "Пожалуйста, сообщите об этом в службу по работе с гостями; необходимая поддержка может быть согласована с кухней.",
        "special_need_vegan": "Пожалуйста, сообщите о ваших пищевых предпочтениях в службу по работе с гостями; подходящие варианты могут быть предложены.",
        "special_need_allergy": "Пожалуйста, сообщите об аллергии в службу по работе с гостями; необходимая поддержка будет организована.",
        "special_need_baby_need": "Пожалуйста, сообщите о потребности в детском питании в службу по работе с гостями; они помогут подобрать подходящие варианты.",
        "special_need_accessibility_need": "Пожалуйста, сообщите о ваших потребностях в доступности в службу по работе с гостями; необходимые договоренности будут организованы.",
        "special_need_default": "Пожалуйста, свяжитесь со службой по работе с гостями по этому вопросу.",
        "fixed_restaurant_info": "- Основной ресторан: завтрак 07:00-10:00, поздний завтрак 10:00-10:30, обед 12:30-14:00, ужин 19:00-21:00, мини-ночной буфет 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: по записи и платный.\n- Sinton BBQ: 13:00-22:00 (по понедельникам закрыт).\nСнеки и кафе:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss напитки 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nБары:\n- Pool Bar 10:00-00:00\n- Мороженое 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 и 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Есть частный пляж.\n- Шезлонги, зонты и пляжные полотенца предоставляются бесплатно.\n- Время использования пляжа: 08:30-18:30.\nБассейны:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 и 14:00-16:00\n- Крытый бассейн: 08:00-19:00\n- Также доступны детский бассейн и Dolphin Pool.\n- Сервис полотенец для бассейна и пляжа бесплатный.",
        "fixed_spa_info": "- La Serenite Spa работает с 09:00 до 19:00.\nБесплатные зоны:\n- Сауна\n- Турецкий хаммам\n- Паровая комната\n- Крытый бассейн\nПлатные услуги:\n- Массаж\n- Пилинг\n- Уход за кожей\n- Другие процедуры\nПримечание: Базовое использование влажных зон бесплатно; профессиональные процедуры и терапия — платные.",
        "fixed_animation_info": "- Вечерние акробатические танцевальные шоу, тематические вечера, живая музыка и DJ-выступления.\n- Дневная программа стартует в 10:00 и включает aqua gym, дартс и водное поло.\nДетские активности:\n- Jammies Kids Club / Mini Club: 10:00-12:30 и 14:30-17:00 (4-12 лет)\n- Mini Disco: 20:45-21:00 (4-12 лет)\n- Детская площадка: 07:00-21:00\nПримечание: Программы могут меняться в зависимости от сезона и операционного графика.",
        "fixed_outside_hotel_info": "Для рекомендаций вне отеля лучше обратиться на ресепшн — там подскажут самые актуальные и безопасные варианты. Центр Аланьи находится примерно в 3 км, доступны такси и общественный транспорт.",
    },
}


class LocalizationService:
    def get(self, key: str, language: str) -> str:
        lang = self.normalize_lang(language)
        return TRANSLATIONS[lang].get(key, TRANSLATIONS["tr"].get(key, key))

    @staticmethod
    def normalize_lang(language: str | None) -> str:
        return language if language in TRANSLATIONS else "tr"

    def canonical_fallback(self, language: str | None, reason: str = "safe") -> str:
        lang = self.normalize_lang(language)
        reason_to_key = {
            "safe": "canonical_fallback_safe",
            "upstream_unavailable": "canonical_fallback_unavailable",
            "validation_error": "canonical_fallback_safe",
        }
        key = reason_to_key.get(reason, "canonical_fallback_safe")
        return self.get(key, lang)

