"""Polish UI strings for Viona chatbot (guest-facing pl locale)."""
from typing import Dict

TRANSLATIONS_PL: Dict[str, str] = {
    'chitchat_greeting': 'Dzień dobry, jestem Viona, cyfrową asystentką w hotelu Kaila Beach. W czym mogę pomóc?',
    'chitchat_assistant_intro': 'Jestem Vioną, cyfrową asystentką hotelu Kaila Beach. Pomogę w sprawach usług hotelowych, informacji i praktycznych pytań podczas pobytu.',
    'chitchat_identity_question': 'Jestem Vioną, asystentką stworzoną dla Kaila Beach Hotel. Mogę pomóc w usługach hotelowych, pobycie i ogólnych informacjach.',
    'chitchat_thanks': 'Proszę bardzo. Jeśli pojawią się kolejne pytania dotyczące pobytu w Kaila Beach Hotel, jestem do dyspozycji.',
    'chitchat_farewell': 'Do zobaczenia. Gdy będzie potrzebna pomoc podczas pobytu, jestem tutaj.',
    'chitchat_apology_from_user': 'Nic nie szkodzi. Chętnie dalej pomogę.',
    'chitchat_compliment': 'Dziękuję za miłe słowa. Cieszę się, że mogłam pomóc.',
    'chitchat_how_are_you': 'Dziękuję, czuję się dobrze. Jestem przy Tobie w pytaniach o Kaila Beach Hotel.',
    'chitchat_cancel_command_hint': 'Gdy mówisz „anuluj”, może chodzić o podsumowanie formularza czatu, prośbę o rezerwację lub coś innego. Na ekranie podsumowania 2 oznacza anulowanie. W Kaila Beach rezerwacje i stoliki są załatwiane osobiście przez recepcję i zespoły specjalistów — z przyjemnością poprowadzę Cię do właściwego stanowiska. W czym jeszcze mogę pomóc?',
    'chitchat_confusion_generic': 'Którą część mam wyjaśnić? Mogę podpowiedzieć, co wpisać w sprawie informacji o hotelu, prośby, zgłoszenia awarii lub reklamacji.',
    'chitchat_confusion_after_form_cancel': 'Właśnie anulowałeś(-aś) ekran podsumowania, więc wpis nie został utworzony. Na tym ekranie 1 oznacza potwierdzenie i utworzenie wpisu, 2 — rezygnację. Aby zacząć od nowa, napisz np. „gniazdko nie działa”. W polu imienia i nazwiska podaj proszę dane jak w dokumencie (dwa wyrazy, np. Anna Kowalska).',
    'session_ack_after_cancel': 'Rozumiem. Daj znać, jeśli potrzebujesz pomocy w czymś innym.',
    'session_vazgectim_after_cancel': 'Nie utworzono wpisu. Możesz ponownie uruchomić formularz w czacie dla tego samego tematu lub napisać nową prośbę albo zgłoszenie awarii.',
    'session_reservation_followup_short': 'Sama krótka odpowiedź nie pozwala mi powiązać jej z istniejącą rezerwacją — podaj proszę konkretną datę lub jasne pytanie. W sprawach pobytu i ogólnych ustaleń: recepcja; dla wykwintnych stolików à la carte: Guest Relations; dla spa i masażu: La Serenite Spa — jesteśmy z Tobą na każdym etapie.',
    'session_animation_schedule_followup': 'Dzienny harmonogram animacji i aktywności w aplikacji w sekcji „Animacja i wydarzenia” oraz w informacjach hotelowych zwykle jest taki sam każdego dnia; częściej zmieniają się wieczorne pokazy i tematyczne wieczory, a niektóre dni mogą mieć dodatkowy występ. Dokładne godziny na jutro lub konkretny wieczór potwierdź na aktualnej tablicy przy recepcji lub u zespołu animacji. Godziny Mini Club / Mini Disco mogą zależeć od grupy wiekowej dzieci.',
    'chat_form_cancel_ack_fault': 'Dobrze, anulowałam to zgłoszenie awarii. W każdej chwili możesz utworzyć nowe zgłoszenie awarii, prośbę lub powiadomienie dla hotelu.',
    'chat_form_cancel_ack_request': 'Dobrze, anulowałam tę prośbę. W każdej chwili możesz utworzyć nową prośbę, zgłoszenie awarii lub powiadomienie dla hotelu.',
    'chat_form_cancel_ack_complaint': 'Dobrze, anulowałam tę reklamację. W każdej chwili możesz utworzyć nową reklamację, prośbę lub zgłoszenie awarii.',
    'chat_form_cancel_ack_guest_notification': 'Dobrze, anulowałam to powiadomienie dla hotelu. W każdej chwili możesz utworzyć nowe powiadomienie, prośbę lub zgłoszenie awarii.',
    'chat_form_context_retract_ack': 'Rozumiem — jeśli wpis nie jest potrzebny, to dobra wiadomość. Napisz krótko, w czym jeszcze pomóc: pokój, wyżywienie, aktywności lub recepcja.',
    'chitchat_switch_en': "I'll reply in English from now on. How can I help you?",
    'chitchat_switch_tr': 'Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?',
    'chitchat_switch_de': 'Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?',
    'chitchat_switch_pl': 'Od teraz odpowiadam po polsku. W czym mogę pomóc?',
    'current_time_template': 'Aktualna godzina to {time}.',
    'fault_redirect_message': 'W tej sprawie wypełnij proszę formularz zgłoszenia awarii.',
    'complaint_redirect_message': 'W tej sprawie wypełnij proszę formularz reklamacji.',
    'request_redirect_message': 'Prośbę możesz przekazać przez formularz zgłoszeń.',
    'guest_relations_redirect_message': 'W tej sprawie skontaktuj się proszę z działem Guest Relations.',
    'reception_fallback_message': 'Nie mogłam teraz w pełni przetworzyć wiadomości. Spróbuj napisać krócej — dalej chętnie pomogę.',
    'canonical_fallback_safe': 'Nie mam teraz zweryfikowanych informacji na ten temat. Aby uzyskać najpewniejszą pomoc, skontaktuj się z recepcją.',
    'canonical_fallback_unavailable': 'Chwilowo jestem niedostępna. Spróbuj ponownie za kilka sekund.',
    'chat_fallback_throttled': 'Wysyłasz wiadomości bardzo szybko. Poczekaj kilka sekund i spróbuj ponownie — w pilnych sprawach recepcja zawsze pomoże.',
    'chat_fallback_validation_error': 'Nie mogę przetworzyć pustej wiadomości. Napisz krótkie pytanie lub prośbę.',
    'chat_form_invalid_state_hint': 'Coś przerwało formularz — nic nie zapisano. Opisz krótko prośbę od nowa lub poproś recepcję o pomoc.',
    'recommendation_fish': 'Do ryb i owoców morza polecam Moss Beach Restaurant & Bar na plaży (płatne à la carte) oraz restaurację główną. La Terrace A La Carte wymaga rezerwacji na à la carte.',
    'recommendation_meat': 'Jeśli wolisz mięso lub BBQ, świetnie pasuje Sinton BBQ Restaurant. Restauracje a la carte wymagają rezerwacji.',
    'recommendation_pizza_snack': 'Na pizzę lub przekąski dobre są Dolphin Snack, Gusto Snack i Beach Imbiss.',
    'recommendation_coffee_dessert': 'Na kawę lub deser idealne są Libum Cafe i Lobby Bar.',
    'recommendation_kids_activity': 'Dla dzieci główne opcje to Mini Club, Mini Disco i plac zabaw.',
    'recommendation_romantic_dinner': 'Na romantyczny wieczór pasują La Terrace A La Carte lub Moss Beach Restaurant & Bar nad brzegiem; na à la carte zalecam rezerwację.',
    'recommendation_general_dining': 'Jeśli nie wiesz, co wybrać, na kolację dobre są Sinton BBQ lub restauracja główna; na szybki kęs praktyczne są Dolphin Snack i Gusto Snack.',
    'fault_template_with_device': 'Gdy {device} nie działa, skontaktuj się z recepcją — w hotelu zapewniamy wsparcie techniczne.',
    'fault_template_generic': 'W tej awarii skontaktuj się z recepcją — w hotelu zapewniamy wsparcie techniczne.',
    'complaint_noise': 'Najpierw zgłoś tę reklamację do Guest Relations. W razie potrzeby recepcja też może pomóc w eskalacji.',
    'complaint_cleanliness': 'Najpierw zgłoś problem ze sprzątaniem do Guest Relations; recepcja też może wesprzeć.',
    'complaint_default': 'W tej reklamacji najpierw skontaktuj się z Guest Relations. Możesz też zgłosić sprawę przez recepcję.',
    'complaint_lost_property': (
        'Zgubione rzeczy — przedmioty wartościowe przechowujemy do roku, pozostałe do sześciu miesięcy.\n\n'
        'Zwroty w stylu «zgubiłem», «nie mogę znaleźć», «zginęło» dotyczące rzeczy osobistych (okulary, telefon, zegarek, biżuteria) '
        'to nie awaria pokoju — w poniższym formularzu reklamacji wybierz «Zgubione rzeczy».\n\n'
        'Aby uzyskać najlepszą pomoc, udaj się do Guest Relations lub recepcji. Możesz też wypełnić poniższy formularz reklamacji i opisać sytuację na piśmie — zespół zadba o Twój wpis.'
    ),
    'request_towel': 'W sprawie ręczników skontaktuj się z recepcją.',
    'request_blanket': 'W sprawie dodatkowego koca skontaktuj się z recepcją.',
    'request_water': 'Aby dowieźć wodę lub wodę pitną do pokoju, skontaktuj się z recepcją — zespół zorganizuje dostawę.',
    'request_pillow': 'W sprawie poduszki skontaktuj się z recepcją.',
    'request_housekeeping': 'W sprawach sprzątania i housekeeping skontaktuj się z recepcją — powiadomimy odpowiedni zespół.',
    'request_reception_contact': 'Aby najszybciej rozwiązać sprawę, skontaktuj się bezpośrednio z recepcją.',
    'request_guest_relations_contact': 'W tej sprawie właściwy jest dział Guest Relations. Możesz też połączyć się przez recepcję.',
    'request_transfer': 'W sprawie transferu skontaktuj się z recepcją — pomożemy w organizacji.',
    'request_lunch_box': 'W sprawie Lunch Box poinformuj recepcję najpóźniej do godz. 20:00.',
    'request_spa_booking_contact': 'W sprawie masaży, rytuałów i płatnych zabiegów w La Serenite Spa zapraszamy do bezpośredniego kontaktu z naszym zespołem spa — dobiorą czas i formę wizyty. Recepcja może dyskretnie połączyć, jeśli chcesz. Rezerwacje i pytania do spa — wewnętrzny numer hotelu: 5025.',
    'request_ala_carte_reservation': 'Płatne kolacje i stoliki à la carte są organizowane z troską przez Guest Relations. Skontaktuj się z nimi bezpośrednio; recepcja może też zadbać o płynne wprowadzenie.',
    'request_premium_reservation_reception': 'W sprawie miejsc premium i wykwintnych kolacji recepcja / front office dba o najlepsze skierowanie i przedstawia odpowiedniemu zespołowi lub restauracji.',
    'request_default': 'Przekaż tę prośbę recepcji.',
    'reservation_early_checkin': 'W sprawie wcześniejszego zameldowania skontaktuj się z recepcją.',
    'reservation_late_checkout': 'W sprawie późniejszego wymeldowania skontaktuj się z recepcją.',
    'reservation_room_change': 'W sprawie zmiany pokoju skontaktuj się z recepcją.',
    'reservation_default': 'W Kaila Beach rezerwacje i stoliki są załatwiane osobiście przez recepcję i zespoły specjalistów — z indywidualną troską. W sprawach pobytu i planów: recepcja; stoliki à la carte: Guest Relations; spa i masaż: La Serenite Spa — jesteśmy przy Tobie na każdym etapie.',
    'special_need_celiac': 'Poinformuj Guest Relations o tej sytuacji; kuchnia może zapewnić odpowiednie wsparcie.',
    'special_need_vegan': 'Poinformuj Guest Relations o preferencjach żywieniowych; możemy zaproponować odpowiednie opcje.',
    'special_need_allergy': 'Poinformuj Guest Relations o alergii — zapewnimy potrzebne wskazówki.',
    'special_need_baby_need': 'W sprawie żywienia niemowląt skontaktuj się z Guest Relations — pomogą dobrać opcje.',
    'special_need_accessibility_need': 'Poinformuj Guest Relations o potrzebach dostępności — zadbamy o niezbędne ustalenia.',
    'special_need_default': 'W tej sprawie skontaktuj się z Guest Relations.',
    'guest_notification_policy_hint': 'Powiadomienie dla hotelu możesz wysłać w czacie, wybierając kategorię; w kolejnej wiadomości możesz napisać np. gluten, alergia lub świętowanie.',
    'fixed_restaurant_info': '- Restauracja główna: śniadanie 07:00-10:00, późne śniadanie 10:00-10:30, obiad 12:30-14:00, kolacja 19:00-21:00, mini bufet nocny 23:30-00:00.\n- La Terrace A La Carte: 18:30-20:30 (rezerwacja, płatne).\n- Sinton BBQ: 13:00-22:00 (poniedziałki zamknięte).\nPrzekąski i kawiarnie:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss przekąski 12:00-16:00\n- Beach Imbiss napoje 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBary:\n- Pool Bar 10:00-00:00\n- Lody 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 i 20:00-23:00\n- Dolphin Bar 10:00-17:00',
    'fixed_pool_beach_info': '- Jest prywatna plaża.\n- Leżaki, parasole i ręczniki plażowe są bezpłatne.\n- Godziny plaży: 08:30-18:30.\nBaseny:\n- Trzy baseny zewnętrzne: Relax Pool 08:30-18:30, Aquapark 10:00-12:00 i 14:00-16:00, Dolphin Pool 08:30-18:30.\n- Basen kryty (spa): 08:00-19:00.\n- Płytkie strefy dla dzieci na zewnątrz / w strefie aquaparku.\n- Ratownicy przy basenach i przy morzu.\n- Serwis ręczników do basenu i na plażę jest bezpłatny.',
    'fixed_spa_info': '- Godziny La Serenite Spa: 09:00-19:00.\nStrefy bezpłatne:\n- sauna\n- łaźnia turecka\n- łaźnia parowa\n- basen kryty\nUsługi płatne:\n- masaż\n- peeling\n- pielęgnacja skóry\n- inne zabiegi\nUwaga: podstawowe korzystanie ze stref mokrych jest bezpłatne; profesjonalne zabiegi i terapie są płatne.\n\nAktualne cenniki i PDF zabiegów nie są podawane jako długi tekst w czacie — treści premium są w aplikacji w sekcji „Spa & wellness”. Otwórz stronę przyciskiem poniżej.\n\nRezerwacje i pytania do spa — wewnętrzny numer: 5025.',
    'fixed_kuafor_info': 'W hotelu jest usługa fryzjerska. W sprawie cen, terminów i usług skontaktuj się z panem Savaşem: +90 546 608 16 72.',
    'wayfinding_rag_miss_guest_relations': 'Nie mogę teraz potwierdzić lokalizacji jednym zweryfikowanym zdaniem. Aby uzyskać aktualne, spersonalizowane wskazówki, skontaktuj się z Guest Relations — zespół pomoże z troską. Możesz też otworzyć w aplikacji sekcję „Gdzie” z mapą.',
    'fixed_transfer_module_hint': 'Kaila Beach oferuje dedykowany transfer; w sprawie powitania i trasy skontaktuj się z recepcją / front office. Aktualne stawki, opcje pojazdów i przykładowe trasy nie są podawane jako długi tekst w czacie — treści premium są w module „Transfer”.\n\nOtwórz go przyciskiem poniżej.',
    'fixed_spa_prices_module_hint': 'Ceny zabiegów spa nie są wymieniane w czacie. Aktualny cennik i pakiety są tylko w module „Spa & wellness” — użyj przycisku poniżej.',
    'fixed_restaurants_bars_module_hint': 'Menu Pool Bar, menu Lobby Bar, menu Moss Beach Restaurant oraz cenniki napojów / importowanych alkoholi w barach nie są pokazywane jako długi tekst w czacie; aktualne PDF są w „Restauracje i bary”. Otwórz sekcję przyciskiem poniżej. (Ogólne godziny lokali możesz zapytać jako „godziny restauracji” lub zobaczyć w tym samym module.)',
    'fixed_animation_info': '- Wieczorne pokazy akrobatyczne, tematyczne wieczory, muzyka na żywo i DJ (mogą się różnić wg dnia i sezonu; czasem dodatkowy pokaz).\n- Dzienny harmonogram jest zwykle stały: program od 10:00 z aqua gym, dartem i piłką wodną. Najnowsze brzmienie i godziny są w aplikacji w sekcji „Animacja i wydarzenia”.\nAktywności dla dzieci:\n- Jammies Kids Club / Mini Club: 10:00-12:30 i 14:30-17:00 (wiek 4-12)\n- Mini Disco: 20:45-21:00 (wiek 4-12)\n- Plac zabaw: 07:00-21:00\nUwaga: program wieczorny i dodatkowe pokazy mogą się różnić wg dnia; dokładne informacje u recepcji lub na tablicy animacji.',
    'fixed_outside_hotel_info': 'W sprawie rekomendacji poza hotelem najpewniejsze i aktualne informacje poda recepcja. Centrum Alanii jest ok. 3 km; dostępne są taxi i transport publiczny.',
    'fixed_alanya_discover_intro': 'Alanya to kurort nad Morzem Śródziemnym znany z plaży, zamku i klimatu historycznego. Częste punkty zwiedzania:\n\n• Plaża Kleopatry — drobny piasek i czysta woda\n• Czerwona Wieża i port — symbol miasta\n• Zamek Alanii — panorama ze wzgórza; zachody słońca zapadają w pamięć\n• Rzeka Dim i strefy piknikowe w głębi lądu\n\nHotel jest w Obagöl, ok. 3 km od centrum. Taxi i komunikacja są praktyczne. Godziny otwarcia, bilety i wycieczki organizowane — najpewniej u recepcji.\n\nPrzycisk poniżej otwiera w aplikacji sekcję „Odkryj Alanę” z krótkimi opisami i zdjęciami.',
    'fixed_ice_cream_info': 'Tak, w hotelu jest serwis lodów. Bezpłatnie przy Pool Bar w godz. 15:00-17:00. (Godziny mogą się różnić wg sezonu i operacji.)',
    'fixed_laundry_dry_cleaning_info': 'Pralnia, chemiczna i prasowanie są w hotelu odpłatnie. W sprawie odbioru, czasu realizacji i aktualnych cen skontaktuj się z recepcją lub housekeeping — zajmą się rzeczami i prośbą.',
    'hotel_info_soft_followup_towel': 'Powyższe godziny i zasady karty dotyczą ręczników basenowych / plażowych wydawanych przy punkcie basenu lub plaży. To nie to samo co ręczniki łazienkowe w pokoju.',
    'hotel_info_soft_followup_request_form_hint': 'Aby coś dowieźć do pokoju lub zarejestrować prośbę o zaopatrzenie, napisz wyraźnie w czacie (np. „potrzebuję…”, „proszę przynieść”, „brakuje”, „chcę złożyć prośbę”) lub otwórz formularz Prośby w aplikacji.',
}
