from typing import Dict


TRANSLATIONS: Dict[str, Dict[str, str]] = {
    "tr": {
        "chitchat_greeting": "Merhaba, ben Viona; Kaila Beach Hotel'deki dijital asistanınızım. Size nasıl yardımcı olabilirim?",
        "chitchat_assistant_intro": "Ben Viona — Kaila Beach Hotel için çalışan dijital asistanınızım. Otel hizmetleri ve sorularınızda size yardımcı olabilirim.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "Şu an saat {time}'dir.",
        "fault_redirect_message": "Bu sorun için lütfen Arıza Talep formunu doldurunuz.",
        "complaint_redirect_message": "Bu konu için lütfen Şikayet formunu doldurunuz.",
        "request_redirect_message": "Talebinizi İstek formu üzerinden iletebilirsiniz.",
        "guest_relations_redirect_message": "Bu konu için lütfen Misafir İlişkileri departmanı ile iletişime geçiniz.",
        "reception_fallback_message": "Bu konuda doğrulanmış bilgiye erişemiyorum. Lütfen resepsiyon ile iletişime geçiniz.",
        "fault_template_with_device": "{device} arızası durumunda lütfen resepsiyon ile iletişime geçiniz; otelde teknik destek sağlanmaktadır.",
        "fault_template_generic": "Bu arıza durumu için lütfen resepsiyon ile iletişime geçiniz; otelde teknik destek sağlanmaktadır.",
        "complaint_noise": "Bu şikayetinizi lütfen resepsiyon ile paylaşınız; gerekli yönlendirme sağlanacaktır.",
        "complaint_cleanliness": "Temizlik ile ilgili bu durumu lütfen resepsiyon ile bildiriniz.",
        "complaint_default": "Bu şikayetinizi lütfen resepsiyon ile paylaşınız.",
        "request_towel": "Havlu talebinizi lütfen resepsiyon ile iletiniz.",
        "request_blanket": "Battaniye talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "request_default": "Bu talebinizi lütfen resepsiyon ile paylaşınız.",
        "reservation_early_checkin": "Erken giriş talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "reservation_late_checkout": "Geç çıkış talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "reservation_room_change": "Oda değişikliği talebiniz için lütfen resepsiyon ile iletişime geçiniz.",
        "reservation_default": "Rezervasyonunuzla ilgili bu durum için lütfen resepsiyon ile iletişime geçiniz.",
        "special_need_celiac": "Bu durumunuzu lütfen Misafir İlişkileri departmanına iletiniz; mutfak departmanından uygun destek sağlanabilir.",
        "special_need_vegan": "Beslenme tercihinizi lütfen Misafir İlişkileri departmanına iletiniz; uygun seçenekler konusunda yardımcı olunabilir.",
        "special_need_allergy": "Alerji bilginizi lütfen Misafir İlişkileri departmanına bildiriniz; gerekli yönlendirme sağlanacaktır.",
        "special_need_baby_need": "Bebek beslenmesi ve mama ile ilgili talebinizi lütfen Misafir İlişkileri departmanına iletiniz; uygun seçenekler konusunda yardımcı olacaklardır.",
        "special_need_accessibility_need": "Erişilebilirlik ile ilgili ihtiyacınızı lütfen Misafir İlişkileri departmanına bildiriniz; gerekli düzenlemeler sağlanacaktır.",
        "special_need_default": "Bu durum için lütfen Misafir İlişkileri departmanı ile iletişime geçiniz.",
        "fixed_restaurant_info": "- Ana Restoran: Kahvaltı 07:00-10:00, Geç kahvaltı 10:00-10:30, Öğle yemeği 12:30-14:00, Akşam yemeği 19:00-21:00, Mini gece büfesi 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: Rezervasyonlu ve ücretli.\n- Sinton BBQ: 13:00-22:00 (Pazartesi kapalı).\nSnack ve cafe:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss İçecek 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBarlar:\n- Havuz Bar 10:00-00:00\n- Dondurma Servisi 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 ve 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Özel plaj mevcuttur.\n- Şezlong, şemsiye ve plaj havlusu ücretsizdir.\n- Plaj kullanım saatleri: 08:30-18:30.\nHavuzlar:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 ve 14:00-16:00\n- Kapalı Havuz: 08:00-19:00\n- Çocuk havuzu ve Dolphin Pool da bulunmaktadır.\n- Havuz ve plaj havlusu servisi ücretsizdir.",
        "fixed_spa_info": "- La Serenite Spa kullanım saatleri: 09:00-19:00.\nÜcretsiz alanlar:\n- Sauna\n- Türk hamamı\n- Buhar odası\n- Kapalı havuz\nÜcretli hizmetler:\n- Masaj\n- Peeling\n- Cilt bakımı\n- Diğer bakım hizmetleri\nNot: Temel ıslak alan kullanımı ücretsiz, profesyonel bakım ve terapi hizmetleri ücretlidir.",
        "fixed_animation_info": "- Akşam akrobatik dans şovları, temalı geceler, canlı müzik, DJ performansları.\n- Günlük program 10:00'da başlar; aqua gym, dart, su topu gibi aktiviteler içerir.\nÇocuk aktiviteleri:\n- Jammies Kids Club / Mini Club: 10:00-12:30 ve 14:30-17:00 (4-12 yaş)\n- Mini Disco: 20:45-21:00 (4-12 yaş)\n- Çocuk oyun parkı: 07:00-21:00\nNot: Programlar sezon ve operasyon takvimine göre değişebilir.",
    },
    "en": {
        "chitchat_greeting": "Hello, I'm Viona, your digital assistant at Kaila Beach Hotel. How can I help you?",
        "chitchat_assistant_intro": "I'm Viona, the digital assistant for Kaila Beach Hotel. I can help you with hotel services, information and practical questions during your stay.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "The current time is {time}.",
        "fault_redirect_message": "For this issue, please complete the Fault Report form.",
        "complaint_redirect_message": "For this matter, please complete the Complaint form.",
        "request_redirect_message": "You can submit your request through the Request form.",
        "guest_relations_redirect_message": "For this matter, please contact the Guest Relations department.",
        "reception_fallback_message": "I don’t have verified information about this. Please contact reception for assistance.",
        "fault_template_with_device": "If your {device} is not working, please contact reception; technical support is provided at the hotel.",
        "fault_template_generic": "For this fault, please contact reception; technical support is provided at the hotel.",
        "complaint_noise": "Please report this noise complaint to reception; they will provide the necessary assistance.",
        "complaint_cleanliness": "Please report this cleanliness issue to reception.",
        "complaint_default": "Please share this complaint with reception.",
        "request_towel": "Please contact reception for your towel request.",
        "request_blanket": "Please contact reception for your blanket request.",
        "request_default": "Please share this request with reception.",
        "reservation_early_checkin": "Please contact reception for your early check-in request.",
        "reservation_late_checkout": "Please contact reception for your late check-out request.",
        "reservation_room_change": "Please contact reception for your room change request.",
        "reservation_default": "Please contact reception regarding your reservation request.",
        "special_need_celiac": "Please inform the Guest Relations department about this condition; suitable support can be coordinated with the kitchen.",
        "special_need_vegan": "Please inform the Guest Relations department about your dietary preference; suitable options may be arranged.",
        "special_need_allergy": "Please inform the Guest Relations department about your allergy; necessary guidance will be provided.",
        "special_need_baby_need": "Please contact the Guest Relations department about your baby food needs; they can help arrange suitable options.",
        "special_need_accessibility_need": "Please inform the Guest Relations department about your accessibility needs; the necessary arrangements will be made.",
        "special_need_default": "Please contact the Guest Relations department for this matter.",
        "fixed_restaurant_info": "- Main Restaurant: Breakfast 07:00-10:00, Late breakfast 10:00-10:30, Lunch 12:30-14:00, Dinner 19:00-21:00, Mini night buffet 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: Reservation-only and paid.\n- Sinton BBQ: 13:00-22:00 (closed Mondays).\nSnack and cafe:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss Drinks 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBars:\n- Pool Bar 10:00-00:00\n- Ice Cream Service 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 and 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Private beach available.\n- Sunbeds, umbrellas, and beach towels are free.\n- Beach usage hours: 08:30-18:30.\nPools:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 and 14:00-16:00\n- Indoor Pool: 08:00-19:00\n- Children’s pool and Dolphin Pool are also available.\n- Pool and beach towel service is free.",
        "fixed_spa_info": "- La Serenite Spa hours: 09:00-19:00.\nFree areas:\n- Sauna\n- Turkish bath\n- Steam room\n- Indoor pool\nPaid services:\n- Massage\n- Peeling\n- Skin care\n- Other treatment services\nNote: Basic wet-area use is free; professional care and therapy services are paid.",
        "fixed_animation_info": "- Evening acrobatic dance shows, themed nights, live music, and DJ performances.\n- Daily program starts at 10:00 and includes aqua gym, darts, and water polo.\nChildren’s activities:\n- Jammies Kids Club / Mini Club: 10:00-12:30 and 14:30-17:00 (ages 4-12)\n- Mini Disco: 20:45-21:00 (ages 4-12)\n- Children’s playground: 07:00-21:00\nNote: Programs may vary based on seasonal and operational schedules.",
    },
    "de": {
        "chitchat_greeting": "Hallo, ich bin Viona, Ihre digitale Assistentin im Kaila Beach Hotel. Wie kann ich Ihnen helfen?",
        "chitchat_assistant_intro": "Ich bin Viona, die digitale Assistentin des Kaila Beach Hotels. Ich unterstütze Sie bei Services, Informationen und Fragen rund um Ihren Aufenthalt.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "Die aktuelle Zeit ist {time}.",
        "fault_redirect_message": "Bitte füllen Sie für dieses Problem das Störungsmeldungsformular aus.",
        "complaint_redirect_message": "Bitte füllen Sie für dieses Thema das Beschwerdeformular aus.",
        "request_redirect_message": "Sie können Ihre Anfrage über das Anfrageformular senden.",
        "guest_relations_redirect_message": "Bitte wenden Sie sich für dieses Thema an die Gästebetreuung.",
        "reception_fallback_message": "Ich kann zu diesem Thema keine verifizierten Informationen abrufen. Bitte kontaktieren Sie die Rezeption.",
        "fault_template_with_device": "Bei einem {device}-Defekt wenden Sie sich bitte an die Rezeption; im Hotel wird technischer Support bereitgestellt.",
        "fault_template_generic": "Bei dieser Störung wenden Sie sich bitte an die Rezeption; im Hotel wird technischer Support bereitgestellt.",
        "complaint_noise": "Bitte melden Sie diese Beschwerde zur Lärmsituation an der Rezeption; die notwendige Unterstützung wird bereitgestellt.",
        "complaint_cleanliness": "Bitte melden Sie dieses Reinigungsproblem an der Rezeption.",
        "complaint_default": "Bitte teilen Sie diese Beschwerde der Rezeption mit.",
        "request_towel": "Bitte wenden Sie sich für Ihre Handtuchanfrage an die Rezeption.",
        "request_blanket": "Bitte wenden Sie sich für Ihre Deckenanfrage an die Rezeption.",
        "request_default": "Bitte teilen Sie diese Anfrage der Rezeption mit.",
        "reservation_early_checkin": "Bitte wenden Sie sich für Ihre Bitte um frühen Check-in an die Rezeption.",
        "reservation_late_checkout": "Bitte wenden Sie sich für Ihre Bitte um späten Check-out an die Rezeption.",
        "reservation_room_change": "Bitte wenden Sie sich für Ihren Zimmerwechsel an die Rezeption.",
        "reservation_default": "Bitte wenden Sie sich bezüglich Ihrer Reservierung an die Rezeption.",
        "special_need_celiac": "Bitte informieren Sie die Gästebetreuung über diese Situation; geeignete Unterstützung kann mit der Küche koordiniert werden.",
        "special_need_vegan": "Bitte informieren Sie die Gästebetreuung über Ihre Ernährungspräferenz; passende Optionen können angeboten werden.",
        "special_need_allergy": "Bitte informieren Sie die Gästebetreuung über Ihre Allergie; die notwendige Unterstützung wird bereitgestellt.",
        "special_need_baby_need": "Bitte wenden Sie sich an die Gästebetreuung bezüglich Ihres Bedarfs an Babynahrung; geeignete Optionen können organisiert werden.",
        "special_need_accessibility_need": "Bitte informieren Sie die Gästebetreuung über Ihre Bedürfnisse im Bereich Barrierefreiheit; die notwendigen Vorkehrungen werden getroffen.",
        "special_need_default": "Bitte wenden Sie sich in diesem Fall an die Gästebetreuung.",
        "fixed_restaurant_info": "- Hauptrestaurant: Frühstück 07:00-10:00, Spätfrühstück 10:00-10:30, Mittagessen 12:30-14:00, Abendessen 19:00-21:00, Mini-Nachtbuffet 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: Reservierungspflichtig und kostenpflichtig.\n- Sinton BBQ: 13:00-22:00 (montags geschlossen).\nSnack und Cafe:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss Getränke 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nBars:\n- Pool Bar 10:00-00:00\n- Eis-Service 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 und 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Privater Strand ist vorhanden.\n- Liegen, Sonnenschirme und Strandhandtücher sind kostenlos.\n- Strandnutzung: 08:30-18:30.\nPools:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 und 14:00-16:00\n- Hallenbad: 08:00-19:00\n- Kinderbecken und Dolphin Pool sind ebenfalls verfügbar.\n- Handtuchservice für Pool und Strand ist kostenlos.",
        "fixed_spa_info": "- Öffnungszeiten La Serenite Spa: 09:00-19:00.\nKostenlose Bereiche:\n- Sauna\n- Türkisches Bad\n- Dampfbad\n- Hallenbad\nKostenpflichtige Leistungen:\n- Massage\n- Peeling\n- Hautpflege\n- Weitere Behandlungen\nHinweis: Grundnutzung der Nassbereiche ist kostenlos; professionelle Pflege- und Therapieleistungen sind kostenpflichtig.",
        "fixed_animation_info": "- Abendliche Akrobatik-Tanzshows, Themenabende, Live-Musik und DJ-Performances.\n- Tagesprogramm startet um 10:00 mit Aqua Gym, Dart und Wasserball.\nKinderaktivitäten:\n- Jammies Kids Club / Mini Club: 10:00-12:30 und 14:30-17:00 (4-12 Jahre)\n- Mini Disco: 20:45-21:00 (4-12 Jahre)\n- Kinderspielplatz: 07:00-21:00\nHinweis: Programme können je nach Saison- und Betriebsplan variieren.",
    },
    "ru": {
        "chitchat_greeting": "Здравствуйте! Я Виона, ваш цифровой ассистент в отеле Kaila Beach. Чем могу помочь?",
        "chitchat_assistant_intro": "Я Виона, цифровой ассистент отеля Kaila Beach. Помогу с услугами отеля, информацией и вопросами во время вашего проживания.",
        "chitchat_switch_en": "I'll reply in English from now on. How can I help you?",
        "chitchat_switch_tr": "Bundan sonra Türkçe yanıtlıyorum. Size nasıl yardımcı olabilirim?",
        "chitchat_switch_de": "Ich antworte ab jetzt auf Deutsch. Wie kann ich Ihnen helfen?",
        "chitchat_switch_ru": "Далее буду отвечать по-русски. Чем могу помочь?",
        "current_time_template": "Текущее время: {time}.",
        "fault_redirect_message": "По этой проблеме, пожалуйста, заполните форму заявки о неисправности.",
        "complaint_redirect_message": "По этому вопросу, пожалуйста, заполните форму жалобы.",
        "request_redirect_message": "Вы можете отправить запрос через форму запроса.",
        "guest_relations_redirect_message": "По этому вопросу, пожалуйста, свяжитесь со службой по работе с гостями.",
        "reception_fallback_message": "У меня нет проверенной информации по этому вопросу. Пожалуйста, обратитесь на ресепшн.",
        "fault_template_with_device": "В случае неисправности ({device}) пожалуйста, обратитесь на ресепшн; в отеле предоставляется техническая поддержка.",
        "fault_template_generic": "При этой неисправности, пожалуйста, обратитесь на ресепшн; в отеле предоставляется техническая поддержка.",
        "complaint_noise": "Пожалуйста, сообщите об этой жалобе на шум на ресепшн; вам предоставят необходимую помощь.",
        "complaint_cleanliness": "Пожалуйста, сообщите о проблеме с чистотой на ресепшн.",
        "complaint_default": "Пожалуйста, передайте эту жалобу на ресепшн.",
        "request_towel": "Пожалуйста, обратитесь на ресепшн по вопросу полотенца.",
        "request_blanket": "Пожалуйста, обратитесь на ресепшн по вопросу одеяла.",
        "request_default": "Пожалуйста, передайте этот запрос на ресепшн.",
        "reservation_early_checkin": "Пожалуйста, обратитесь на ресепшн по вопросу раннего заезда.",
        "reservation_late_checkout": "Пожалуйста, обратитесь на ресепшн по вопросу позднего выезда.",
        "reservation_room_change": "Пожалуйста, обратитесь на ресепшн по вопросу смены номера.",
        "reservation_default": "Пожалуйста, обратитесь на ресепшн по вашему запросу по бронированию.",
        "special_need_celiac": "Пожалуйста, сообщите об этом в службу по работе с гостями; необходимая поддержка может быть согласована с кухней.",
        "special_need_vegan": "Пожалуйста, сообщите о ваших пищевых предпочтениях в службу по работе с гостями; подходящие варианты могут быть предложены.",
        "special_need_allergy": "Пожалуйста, сообщите об аллергии в службу по работе с гостями; необходимая поддержка будет организована.",
        "special_need_baby_need": "Пожалуйста, сообщите о потребности в детском питании в службу по работе с гостями; они помогут подобрать подходящие варианты.",
        "special_need_accessibility_need": "Пожалуйста, сообщите о ваших потребностях в доступности в службу по работе с гостями; необходимые договоренности будут организованы.",
        "special_need_default": "Пожалуйста, свяжитесь со службой по работе с гостями по этому вопросу.",
        "fixed_restaurant_info": "- Основной ресторан: завтрак 07:00-10:00, поздний завтрак 10:00-10:30, обед 12:30-14:00, ужин 19:00-21:00, мини-ночной буфет 23:30-00:00.\n- La Terrace A La Carte: 18:30-21:00.\n- Mare Restaurant: по записи и платный.\n- Sinton BBQ: 13:00-22:00 (по понедельникам закрыт).\nСнеки и кафе:\n- Dolphin Snack 12:00-16:00\n- Beach Imbiss Snack 12:00-16:00\n- Beach Imbiss напитки 10:00-17:00\n- Gusto Snack 11:00-18:00\n- Libum Cafe 11:00-18:00\n- Moss Beach Restaurant & Bar 10:00-19:00\nБары:\n- Pool Bar 10:00-00:00\n- Мороженое 15:00-17:00\n- Lobby Bar 10:00-00:00\n- Aqua Bar 10:00-18:00 и 20:00-23:00\n- Dolphin Bar 10:00-17:00",
        "fixed_pool_beach_info": "- Есть частный пляж.\n- Шезлонги, зонты и пляжные полотенца предоставляются бесплатно.\n- Время использования пляжа: 08:30-18:30.\nБассейны:\n- Relax Pool: 08:30-18:30\n- Aquapark: 10:00-12:00 и 14:00-16:00\n- Крытый бассейн: 08:00-19:00\n- Также доступны детский бассейн и Dolphin Pool.\n- Сервис полотенец для бассейна и пляжа бесплатный.",
        "fixed_spa_info": "- La Serenite Spa работает с 09:00 до 19:00.\nБесплатные зоны:\n- Сауна\n- Турецкий хаммам\n- Паровая комната\n- Крытый бассейн\nПлатные услуги:\n- Массаж\n- Пилинг\n- Уход за кожей\n- Другие процедуры\nПримечание: Базовое использование влажных зон бесплатно; профессиональные процедуры и терапия — платные.",
        "fixed_animation_info": "- Вечерние акробатические танцевальные шоу, тематические вечера, живая музыка и DJ-выступления.\n- Дневная программа стартует в 10:00 и включает aqua gym, дартс и водное поло.\nДетские активности:\n- Jammies Kids Club / Mini Club: 10:00-12:30 и 14:30-17:00 (4-12 лет)\n- Mini Disco: 20:45-21:00 (4-12 лет)\n- Детская площадка: 07:00-21:00\nПримечание: Программы могут меняться в зависимости от сезона и операционного графика.",
    },
}


class LocalizationService:
    def get(self, key: str, language: str) -> str:
        lang = language if language in TRANSLATIONS else "tr"
        return TRANSLATIONS[lang].get(key, TRANSLATIONS["tr"].get(key, key))

